/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Enterprise;

import java.awt.CardLayout;
import java.awt.GridLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneLayout;
import org.eclipse.persistence.tools.profiler.Profile;

/**
 *
 * @author Alex
 */
public class Client extends javax.swing.JPanel {

    /**
     * Creates new form Client
     */
    Interface ventana;
    
    ArrayList<Suscripcion> storage;
    ArrayList<Suscripcion> view;
    CardLayout c;
    PPanel p;
    public Client(Interface ventana) {
        p=new PPanel();
        c=new CardLayout();
        this.ventana=ventana;
        
        initComponents();
        backgrund.add(Spanel,"1");
        backgrund.add(p,"2");
        
        panel.setLayout(new GridLayout(4,2));
        storage=new ArrayList();
        //this.panel.add(new Suscripcion());
        new Date(1,2,2020);
        new Date();
        //this.panel.add(new Tabla("Pandenometrics",new ImageIcon(getClass().getResource("/Imagenes/people.png")),true));
        //this.panel.add(new Tabla("PsocialisManager",new ImageIcon(getClass().getResource("/Imagenes/estadisticas.png")),true));
        //this.panel.add(new Tabla("Calculadora3000",new ImageIcon(getClass().getResource("/Imagenes/calcular.png")),true));
        
        this.panel.add(new Suscripcion("Pandenometrics",new Date(),new Date(),10000,new ImageIcon(getClass().getResource("/Imagenes/people.png")),true));
        this.panel.add(new Suscripcion("PsocialisManager",new Date(),new Date(),10000,new ImageIcon(getClass().getResource("/Imagenes/estadisticas.png")),true));
        this.panel.add(new Suscripcion("Calculadora3000",new Date(),new Date(),1000000,new ImageIcon(getClass().getResource("/Imagenes/calcular.png")),true));
        this.panel.add(new Suscripcion("PsocialisManager",new Date(),new Date(),10000,new ImageIcon(getClass().getResource("/Imagenes/estadisticas.png")),true));
        this.panel.add(new Suscripcion("Calculadora3000",new Date(),new Date(),1000000,new ImageIcon(getClass().getResource("/Imagenes/calcular.png")),true));
        this.panel.add(new Suscripcion("PsocialisManager",new Date(),new Date(),10000,new ImageIcon(getClass().getResource("/Imagenes/estadisticas.png")),true));
        this.panel.add(new Suscripcion("Calculadora3000",new Date(),new Date(),1000000,new ImageIcon(getClass().getResource("/Imagenes/calcular.png")),true));
        
        //c.show(, "1");
        //this.panel.add(new Suscripcion("Carshop",new Date(),new Date()));
        /*
        software.add(0,new Software("MusicCar",true));
        this.panel.add(software.get(0));
        software.add(0,new Software("2CarShop",false,"App de Renta de autos"));
        this.panel.add(software.get(0));
        software.add(0,new Software("1MusicCar",true,"App de musica"));
        this.panel.add(software.get(0));
        software.add(0,new Software("1MusicState",true,"App de musica estatal"));
        this.panel.add(software.get(0));
        software.add(0,new Software("ClothesShop",true,"Tienda de ropa"));
        this.panel.add(software.get(0));*/
        ventana.isclient(true);
        
    }
    public void storage(Suscripcion [] _s){
        for(int i=0;i<_s.length;i++){
            storage.add(_s[i]);
        }
    }
    public Suscripcion search(){
        
    
        return null;
    }
   
    public void isIn(int x,int y){
        /*for(int i=0;i<software.size();i++){
            if(software.get(i).getX() + x<= software.get(i).getX() + software.get(i).getWidth()){
                if(software.get(i).getHeight() + y<= software.get(i).getY() + software.get(i).getHeight()){   
                }
            }
        }
        */
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        ajustes = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Spanel = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        backgrund = new javax.swing.JPanel(c);
        buscadorText = new javax.swing.JTextField();
        buttonAll = new javax.swing.JButton();
        buttonActive = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBackground(new java.awt.Color(137, 44, 220));
        setPreferredSize(new java.awt.Dimension(1200, 900));

        ajustes.setText("perfil");
        ajustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajustesActionPerformed(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar_1.png"))); // NOI18N
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar1.png"))); // NOI18N
        exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar2.png"))); // NOI18N
        exit.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar2.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sen1.png"))); // NOI18N
        jLabel1.setText(" ");

        Spanel.setBackground(new java.awt.Color(15, 76, 117));
        Spanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 76, 117), 1, true));
        Spanel.setToolTipText("");
        Spanel.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 76, 117), 1, true));
        Spanel.setPreferredSize(new java.awt.Dimension(1000, 750));

        panel.setBackground(new java.awt.Color(15, 76, 117));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        Spanel.setViewportView(panel);

        backgrund.setPreferredSize(new java.awt.Dimension(1000, 750));

        javax.swing.GroupLayout backgrundLayout = new javax.swing.GroupLayout(backgrund);
        backgrund.setLayout(backgrundLayout);
        backgrundLayout.setHorizontalGroup(
            backgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        backgrundLayout.setVerticalGroup(
            backgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        buscadorText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscadorText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscadorTextKeyPressed(evt);
            }
        });

        buttonAll.setText("Todos");

        buttonActive.setText("Activas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buscadorText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(buttonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(buttonActive, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(ajustes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backgrund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(Spanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscadorText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAll, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonActive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ajustes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backgrund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(Spanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void ajustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajustesActionPerformed
        c.show(backgrund,"2");
    }//GEN-LAST:event_ajustesActionPerformed

    private void buscadorTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorTextKeyPressed
        
    }//GEN-LAST:event_buscadorTextKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Spanel;
    private javax.swing.JButton ajustes;
    private javax.swing.JPanel backgrund;
    private javax.swing.JTextField buscadorText;
    private javax.swing.JButton buttonActive;
    private javax.swing.JButton buttonAll;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
