/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Enterprise;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;  
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Alex
 */
/**
 * Esta clase contiene una mezcla de atributos de suscripcion y software
 * 
 * 
 */
public class Employ extends javax.swing.JPanel {

    /**
     * Creates new form Suscripcion
     */
    
    
    public Employ() {
        SimpleDateFormat formatter = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("es_ES")); 
        initComponents();
        name.setText("sin nombre");
        equipo.setText("A 0");
        rango.setText("A 0");
        equipo.setText("A 0");
        equipo.setText("A 0");
        setScale(state,new ImageIcon(getClass().getResource("/Imagenes/multiply.png")),25,25);
        this.setBackground(Color.decode("0x0f4c75"));
        setScale(imageLabel,new ImageIcon(getClass().getResource("/Imagenes/desconocido.png")),150,150);
        
        
    }
    /**
    * @param name nombre del software
     * @param f1 fecha de cobro.
     * @param f2 fecha de termino.
     * @param _value valor de la suscripcion.
     * @param _state estado de la suscripcion.
     */
    public Employ(String _name,Date f1,Date f2,int _value,boolean _state) {
        SimpleDateFormat formatter = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("es_ES")); 
        initComponents();
        name.setText(_name);
        
        if(_state){
            setScale(state,new ImageIcon(getClass().getResource("/Imagenes/check.png")),25,25);
      
        }
        else {setScale(state,new ImageIcon(getClass().getResource("/Imagenes/multiply.png")),25,25);
        this.setBackground(Color.decode("0x0f4c75"));
        }
        
    }
    /**
    * @param name nombre del software
     * @param f1 fecha de cobro.
     * @param f2 fecha de termino.
     * @param _value valor de la suscripcion.
     * @param icon icono del software.
     */
    public Employ(String _name,Date f1,Date f2,int _value,ImageIcon icon) {
        SimpleDateFormat formatter = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("es_ES")); 
        
        initComponents();
        name.setText(_name);
        
        setScale(state,new ImageIcon(getClass().getResource("/Imagenes/multiply.png")),25,25);
        this.setBackground(Color.decode("0x0f4c75"));
        setScale(imageLabel,icon,150,150);
        
    }
    /**
    * @param name nombre del software
     * @param f1 fecha de cobro.
     * @param f2 fecha de termino.
     * @param _value valor de la suscripcion.
     * @param icon icono del software.
     * @param _state estado de la suscripcion.
     */
    public Employ(String _name,Date f1,Date f2,int _value,ImageIcon icon,boolean _state) {
        SimpleDateFormat formatter = new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("es_ES")); 
        initComponents();
        name.setText(_name);
        setScale(imageLabel,icon,150,150);
        
        if(_state){
            setScale(state,new ImageIcon(getClass().getResource("/Imagenes/check.png")),25,25);
      
        }
        else {setScale(state,new ImageIcon(getClass().getResource("/Imagenes/multiply.png")),25,25);
        this.setBackground(Color.decode("0x0f4c75"));
        }
        }
    private void setScale(JLabel label,ImageIcon icon,int x,int y){
        Image image=icon.getImage();
        Image newimg= image.getScaledInstance(x,y, Image.SCALE_SMOOTH);
        ImageIcon icon1=new ImageIcon(newimg);
        label.setIcon(icon1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        sueldo = new javax.swing.JLabel();
        rango = new javax.swing.JLabel();
        antiguedad = new javax.swing.JLabel();
        equipo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(188, 111, 241));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 38, 44), 1, true));
        setPreferredSize(new java.awt.Dimension(500, 250));

        name.setFont(new java.awt.Font("Bangers", 0, 24)); // NOI18N
        name.setForeground(new java.awt.Color(82, 5, 123));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Nombre");

        imageLabel.setText(" ");

        sueldo.setFont(new java.awt.Font("Bangers", 0, 18)); // NOI18N
        sueldo.setForeground(new java.awt.Color(137, 44, 220));
        sueldo.setText("Sueldo:");

        rango.setFont(new java.awt.Font("Bangers", 0, 18)); // NOI18N
        rango.setForeground(new java.awt.Color(137, 44, 220));
        rango.setText("Rango");

        antiguedad.setFont(new java.awt.Font("Bangers", 0, 18)); // NOI18N
        antiguedad.setForeground(new java.awt.Color(137, 44, 220));
        antiguedad.setText("Antiguedad:");

        equipo.setFont(new java.awt.Font("Bangers", 0, 18)); // NOI18N
        equipo.setForeground(new java.awt.Color(137, 44, 220));
        equipo.setText("Equipo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rango, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(antiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(rango, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(antiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel antiguedad;
    private javax.swing.JLabel equipo;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel rango;
    private javax.swing.JLabel state;
    private javax.swing.JLabel sueldo;
    // End of variables declaration//GEN-END:variables
}
