/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Enterprise;

/**
 *
 * @author Alex
 */
public class PPanel extends javax.swing.JPanel {

    /**
     * Creates new form profile
     */
    public PPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Img = new javax.swing.JLabel();
        clientName = new javax.swing.JLabel();
        clientRut = new javax.swing.JLabel();
        clientmail = new javax.swing.JLabel();
        clientRut1 = new javax.swing.JLabel();
        rutField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        mailField = new javax.swing.JTextField();
        phonelField = new javax.swing.JTextField();
        addPay = new javax.swing.JButton();
        editProfile1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(82, 5, 123));
        setToolTipText("");

        Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/unKnown.png"))); // NOI18N

        clientName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clientName.setForeground(new java.awt.Color(188, 111, 241));
        clientName.setText("Nombre: Nombre Completo");

        clientRut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clientRut.setForeground(new java.awt.Color(188, 111, 241));
        clientRut.setText("Telefono:+56911111111");

        clientmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clientmail.setForeground(new java.awt.Color(188, 111, 241));
        clientmail.setText("Rut:000000000-0");

        clientRut1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clientRut1.setForeground(new java.awt.Color(188, 111, 241));
        clientRut1.setText("Correo:mc@gmail.com");

        rutField.setBackground(new java.awt.Color(137, 44, 220));
        rutField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rutField.setToolTipText("");

        nameField.setBackground(new java.awt.Color(137, 44, 220));
        nameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameField.setToolTipText("");

        mailField.setBackground(new java.awt.Color(137, 44, 220));
        mailField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mailField.setToolTipText("");

        phonelField.setBackground(new java.awt.Color(137, 44, 220));
        phonelField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phonelField.setToolTipText("");

        addPay.setBackground(new java.awt.Color(137, 44, 220));
        addPay.setText("Agregar metodo de Pago");

        editProfile1.setBackground(new java.awt.Color(137, 44, 220));
        editProfile1.setText("Editar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Img, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clientmail, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientRut, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientRut1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phonelField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rutField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(editProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(addPay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(244, 244, 244))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(clientmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(rutField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(clientRut1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Img, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(phonelField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(clientRut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Img;
    private javax.swing.JButton addPay;
    private javax.swing.JLabel clientName;
    private javax.swing.JLabel clientRut;
    private javax.swing.JLabel clientRut1;
    private javax.swing.JLabel clientmail;
    private javax.swing.JButton editProfile1;
    private javax.swing.JTextField mailField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phonelField;
    private javax.swing.JTextField rutField;
    // End of variables declaration//GEN-END:variables
}
