/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Enterprise;

import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Alex
 */
public class Tabla extends javax.swing.JPanel {
    private JLabel title;
    private JLabel img;
    private JLabel state;
    public Tabla(String _title,ImageIcon _img,Boolean b){
        title=new JLabel(_title);
        img=new JLabel();
        state=new JLabel();
        initComponents();
        title.setFont(new Font("/Banger.tff",3,1));
      
        title.setBounds(20,20,200,50);
        BooleanLabel(b);
        state.setBounds(220,20, 25, 25);
        setScale(img,_img,150,150);
        img.setBounds(20,70,200,50);
        
        
    }
    private void BooleanLabel(Boolean b) {
        if(b){
           this.setScale(state,new ImageIcon(getClass().getResource("/Imagenes/check.png")),25,5);
        }
        else{
           this.setScale(state,new ImageIcon(getClass().getResource("/Imagenes/multiply.png")),25,25); 
        }
    }
    private void setScale(JLabel label,ImageIcon icon,int x,int y){
        Image image=icon.getImage();
        Image newimg= image.getScaledInstance(x,y, Image.SCALE_SMOOTH);
        ImageIcon icon1=new ImageIcon(newimg);
        label.setIcon(icon1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(188, 111, 241));
        setPreferredSize(new java.awt.Dimension(500, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
